import { ObjectUtil } from '@/utils';

export class AllSetting {
  webListen = '';
  webDomain = '';
  webPort = 2053;
  webCertFile = '';
  webKeyFile = '';
  webBasePath = '/';
  sessionMaxAge = 360;
  trustedProxyCIDRs = '127.0.0.1/32,::1/128';
  panelOutbound = '';
  pageSize = 25;
  expireDiff = 0;
  trafficDiff = 0;
  remarkTemplate = '{{INBOUND}}-{{EMAIL}}|📊{{TRAFFIC_LEFT}}|⏳{{DAYS_LEFT}}D';
  subShowIdentityOnAllLinks = false;
  datepicker: 'gregorian' | 'jalalian' = 'gregorian';
  tgBotEnable = false;
  tgBotToken = '';
  tgBotAPIServer = '';
  tgBotChatId = '';
  tgRunTime = '@daily';
  tgBotBackup = false;
  tgCpu = 80;
  tgMemory = 80;
  tgLang = 'en-US';
  twoFactorEnable = false;
  twoFactorToken = '';
  xrayTemplateConfig = '';
  subEnable = true;
  subJsonEnable = false;
  subJsonAutoDetect = false;
  subJsonAlwaysArray = false;
  subJsonUserAgentRegex = '';
  subClashAutoDetect = false;
  subClashUserAgentRegex = '';
  subTitle = '';
  subSupportUrl = '';
  subProfileUrl = '';
  subAnnounce = '';
  subMaintenanceEnable = false;
  subMaintenanceMode: 'notice' | 'fallback' = 'notice';
  subMaintenanceMessage = '🔧 Server maintenance in progress';
  subMaintenanceFallbackLinks = '';
  subEnableRouting = false;
  subRoutingRules = '';
  subIncyEnableRouting = false;
  subIncyRoutingRules = '';
  subStreisandEnableRouting = true;
  subStreisandRoutingRules = 'streisand://aW1wb3J0L3JvdXRlOi8vWW5Cc2FYTjBNRERVQVFJREJBVUdCd2hVYm1GdFpWUjFkV2xrWG1SdmJXRnBibE4wY21GMFpXZDVWWEoxYkdWelcwbHlZVzRnUkdseVpXTjBYeEFrTkRkRE5ETTFNa010UmpJeE1TMDBPVVE1TFRreVFqQXRPVEZFTUVSRlJEVXdNalk1WEVsUVNXWk9iMjVOWVhSamFLVUpFQlVaSGRNS0N3d05EZzlYYm1WMGQyOXlhMVJ3YjNKMFcyOTFkR0p2ZFc1a1ZHRm5VM1ZrY0ZNME5ETlZZbXh2WTJ2U0VRd1NGRkpwY0tFVFhXZGxiMmx3T25CeWFYWmhkR1ZXWkdseVpXTjAwaFlNRnhSV1pHOXRZV2x1b1JoZkVBOW5aVzl6YVhSbE9uQnlhWFpoZEdYU0Znd2FGS0liSEZsa2IyMWhhVzQ2YVhKZkVCTm5aVzl6YVhSbE9tTmhkR1ZuYjNKNUxXbHkwaEVNSGhTaEgxaG5aVzlwY0RwcGNnQUlBQkVBRmdBYkFDb0FNQUE4QUdNQWNBQjJBSDBBaFFDS0FKWUFtZ0NlQUtRQXFRQ3NBSzRBdkFEREFNZ0F6d0RSQU9NQTZBRHJBUFVCQ3dFUUFSSUFBQUFBQUFBQ0FRQUFBQUFBQUFBZ0FBQUFBQUFBQUFBQUFBQUFBQUFCR3c9PQ==';
  subListen = '';
  subPort = 2096;
  subPath = '/sub/';
  subJsonPath = '/json/';
  subClashEnable = false;
  subClashPath = '/clash/';
  subDomain = '';
  externalTrafficInformEnable = false;
  externalTrafficInformURI = '';
  restartXrayOnClientDisable = true;
  anomalyEnable = false;
  anomalySpikeMBPerMinute = 1024;
  anomalySustainedMBPerMinute = 512;
  anomalySustainedMinutes = 10;
  anomalySharedIPThreshold = 5;
  anomalyAction: 'alert' | 'disable' | 'throttle' = 'alert';
  anomalyActionMinutes = 30;
  anomalyThrottleInboundId = 0;
  anomalyCooldownMinutes = 60;
  anomalyHistoryDays = 30;
  scheduledRestartEnable = false;
  scheduledRestartInterval = 24;
  scheduledRestartUnit: 'minutes' | 'hours' | 'days' = 'hours';
  scheduledRestartPanel = false;
  scheduledRestartTimezone: 'local' | 'tehran' = 'local';
  scheduledRestartLastAt = 0;
  scheduledRestartLastTarget = '';
  scheduledRestartLastSuccess = false;
  scheduledRestartLastMessage = '';
  xrayHealthEnable = false;
  xrayHealthFailureThreshold = 2;
  xrayHealthRestartCooldown = 5;
  xrayHealthMaxRestarts = 3;
  xrayHealthWindowMinutes = 30;
  subCertFile = '';
  subKeyFile = '';
  subUpdates = 12;
  subEncrypt = true;
  subURI = '';
  subJsonURI = '';
  subClashURI = '';
  subClashEnableRouting = false;
  subClashRules = '';
  subJsonMux = '';
  subJsonRules = '';
  subJsonFinalMask = '';
  subThemeDir = '';
  subHideSettings = false;

  timeLocation = 'Local';

  ldapEnable = false;
  ldapHost = '';
  ldapPort = 389;
  ldapUseTLS = false;
  ldapInsecureSkipVerify = false;
  ldapBindDN = '';
  ldapPassword = '';
  ldapBaseDN = '';
  ldapUserFilter = '(objectClass=person)';
  ldapUserAttr = 'mail';
  ldapVlessField = 'vless_enabled';
  ldapSyncCron = '@every 1m';
  ldapFlagField = '';
  ldapTruthyValues = 'true,1,yes,on';
  ldapInvertFlag = false;
  ldapInboundTags = '';
  ldapAutoCreate = false;
  ldapAutoDelete = false;
  ldapDefaultTotalGB = 0;
  ldapDefaultExpiryDays = 0;
  ldapDefaultLimitIP = 0;
  tgEnabledEvents = 'login.attempt,cpu.high';
  smtpEnable = false;
  smtpHost = '';
  smtpPort = 587;
  smtpUsername = '';
  smtpPassword = '';
  smtpFrom = '';
  smtpFromName = '';
  smtpTo = '';
  smtpEncryptionType = 'starttls';
  smtpEnabledEvents = 'login.attempt,cpu.high';
  smtpCpu = 80;
  smtpMemory = 80;
  outboundDownThreshold = 3;
  hasTgBotToken = false;
  hasTwoFactorToken = false;
  hasLdapPassword = false;
  hasApiToken = false;
  hasWarpSecret = false;
  hasNordSecret = false;
  hasSmtpPassword = false;
  clearTgBotToken = false;
  clearLdapPassword = false;
  clearSmtpPassword = false;

  constructor(data?: unknown) {
    if (data != null) {
      ObjectUtil.cloneProps(this, data);
    }
    const cpu = Math.round(Number(this.tgCpu));
    this.tgCpu = Number.isFinite(cpu) ? Math.min(100, Math.max(0, cpu)) : 80;
    const threshold = Math.round(Number(this.outboundDownThreshold));
    this.outboundDownThreshold = Number.isFinite(threshold) ? Math.min(100, Math.max(1, threshold)) : 3;
  }

  equals(other: AllSetting): boolean {
    return ObjectUtil.equals(this, other);
  }
}
